import PDFDocument from "pdfkit"



export const generatePDFReport = (res, reportData) => {

    const {
        userRequirement,
        products,
        recommendation,
        reviewInsights
    } = reportData


    const doc = new PDFDocument({ margin: 50 })

    res.setHeader("Content-Type", "application/pdf")
    res.setHeader(
        "Content-Disposition",
        "attachment; filename=shopiq_report.pdf"
    )

    doc.pipe(res)



    // TITLE
    doc
        .fontSize(24)
        .text("ShopIQ AI Shopping Decision Report", {
            align: "center"
        })

    doc.moveDown(2)



    // USER REQUIREMENT
    doc
        .fontSize(16)
        .text("User Requirement")

    doc
        .fontSize(12)
        .text(userRequirement)

    doc.moveDown(2)



    // PRODUCTS SECTION
    doc
        .fontSize(16)
        .text("Compared Products")

    doc.moveDown()

    products.forEach((product, index) => {

        doc
            .fontSize(14)
            .text(`${index + 1}. ${product.title}`)

        doc
            .fontSize(12)
            .text(`Price: ₹${product.price}`)

        doc.text(`Rating: ${product.rating}`)

        doc.text(`Category: ${product.category}`)

        doc.moveDown()

    })



    // REVIEW INSIGHTS
    if (reviewInsights) {

        doc
            .fontSize(16)
            .text("Review Insights")

        doc
            .fontSize(12)
            .text(reviewInsights)

        doc.moveDown(2)

    }



    // FINAL RECOMMENDATION
    doc
        .fontSize(16)
        .text("AI Recommendation")

    doc
        .fontSize(12)
        .text(recommendation)

    doc.moveDown()



    // FOOTER
    doc
        .moveDown(2)
        .fontSize(10)
        .text(
            "Generated by ShopIQ — Your Personal AI Shopping Companion",
            { align: "center" }
        )



    doc.end()

}